@baseUrl = https://api.github.com
@token = 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
@acceptHeader = application/vnd.github.v3.html+json

GET {{baseUrl}}/user/starred
    ?page=1
Authorization: bearer {{token}}
Accept: {{acceptHeader}}

###

GET {{baseUrl}}/search/repositories
    ?q=flutter
    &page=1
Authorization: bearer {{token}}
Accept: {{acceptHeader}}


###

GET {{baseUrl}}/repos/flutter/flutter/readme
Authorization: bearer {{token}}
Accept: {{acceptHeader}}

